languages:
  Ruby: true
  JavaScript: true
engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Metrics/AbcSize:
        enabled: false
      Rubocop/Metrics/ClassLength:
        enabled: false
      Rubocop/Style/IndentationConsistency:
        enabled: false
      Rubocop/Style/TrailingWhitespace:
        enabled: false
      Rubocop/Lint/AmbiguousRegexpLiteral:
        enabled: false
    exclude_fingerprints:
    - f671155df1b448b678e8a7368d4ef4cf
    - 9536ae61d580ef18029cc6350cef40bd
  eslint:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.jsx"
  - Gemfile.lock
exclude_paths:
- "features/step_definitions/web_steps.rb"
- "features/step_definitions/email_steps.rb"
- "db/schema.rb"
- "spec/teaspoon_env.rb"
- "features/step_definitions/web_steps.rb"
- "features/support/paths.rb"
- "db/fixtures/development/01_users.rb"
- "db/fixtures/production/01_users.rb"
- "db/fixtures/development/01_users.rb"