language: ruby
cache: bundler

rvm:
  - 2.2.2

addons:
  postgresql: '9.3'

before_script:
  - cp config/database.yml.travis config/database.yml

script: 
  - 'bundle exec rake db:create'
  - 'bundle exec rake db:migrate'
  - 'CODECLIMATE_REPO_TOKEN=a98985a878ddbe580a6b0ad6b29f7d9a4343b46e631d5c965bd4166039ed6f57 bundle exec rake'

notifications:
  email:
    recipients:
      - sebastian.schkudlara@vizzuality.com
    on_failure: change
    on_success: never

addons:
  code_climate:
    repo_token: a98985a878ddbe580a6b0ad6b29f7d9a4343b46e631d5c965bd4166039ed6f57