language: ruby
cache: bundler

rvm:
  - 2.2.2

addons:
  postgresql: '9.3'

before_script:
  - cp config/database.yml.travis config/database.yml

script: 
  - 'bundle exec rake db:create'
  - 'bundle exec rake db:migrate'
  - 'bundle exec rake'

notifications:
  email:
    recipients:
      - sebastian.schkudlara@vizzuality.com
    on_failure: change
    on_success: never